image: eclipse-temurin:17-jdk-alpine

stages:
  - building
  - testing
  - publishing

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: building
  script:
    - sh gradlew -PapplicationVersion=${CI_COMMIT_TAG} build
  coverage: '/Line Coverage: \d+\.\d+%/'
  artifacts:
    paths:
      - .gradle
      - build

    expire_in: 3 days
    when: always

int-test:
  stage: testing
  script:
    - sh gradlew intTest
  allow_failure: true
  when: manual
  artifacts:
    paths:
      - .gradle
      - build

    expire_in: 3 days
    when: on_failure

publish:
  stage: publishing
  script:
    - sh gradlew -PapplicationVersion=${CI_COMMIT_TAG} publish
  only:
    - tags