version: '3.7'
services:
  aws:
    image: 'localstack/localstack:1.3.1'
    container_name: 'localstack'
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=eu-central-1
      - AWS_DEFAULT_REGION=eu-central-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4563-4599:4563-4599'
    volumes:
      - ./src/intTest/resources/localstack:/etc/localstack/init/ready.d:ro