spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    validationQuery: SELECT 1
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: false
      hibernate:
        ddl-auto: validate
        use-new-id-generator-mappings: true
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
  data:
    rest:
      base-path: /api/v2/data

cloud:
  aws:
    credentials:
      access-key: accesskey #can be anything, ignored by localstack
      secret-key: secretkey #can be anything, ignored by localstack
    region:
      static: eu-central-1  # respected by SQS service
    queue:
      uri: http://localhost:4566
    s3:
      uri: http://localhost:4566
      bucket: file-upload-test

messaging:
  file-upload-event-queue: http://localhost:4566/000000000000/test-bogie-inspect-file-upload-event
  image-detection-job-queue: http://localhost:4566/000000000000/test-bogie-inspect-detection-job-queue
  image-detection-job-result-queue: http://localhost:4566/000000000000/test-bogie-inspect-detection-job-result-queue

security:
  user: bogie
  password: secret


---
spring:
  config:
    activate:
      on-profile: aws
messaging:
  file-upload-event-queue: https://sqs.eu-central-1.amazonaws.com/426550334429/dev-bogie-inspect-file-upload-event1
  image-detection-job-queue: https://sqs.eu-central-1.amazonaws.com/426550334429/dev-bogie-inspect-image-detection-task1
  image-detection-job-result: https://sqs.eu-central-1.amazonaws.com/426550334429/dev-bogie-inspect-image-detection-result1

---
spring:
  config:
    activate:
      on-profile: postgres
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bogieinspect
    driverClassName: org.postgresql.Driver
    username: postgres
    password: deb.deb
    validationQuery: SELECT 1