spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    validationQuery: SELECT 1
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: false
      hibernate:
        ddl-auto: validate
        use-new-id-generator-mappings: true
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
